### ISSUE TITLE
Resizable table

### ISSUE THREAD

**Issue by ruzickap** [tnwhitwell/hugo-startpage-theme#1]
Hello.

It looks like the table is not resizable:

```
$ cat links.yml
---
- name: Test 12345678901234567890 12345678901234567890
  colour: blue # (a valid mdl color name)
  sections: # A section
  - links:
    - title: Test 12345678901234567890 12345678901234567890
      url: https://www.example.com
```

See the screenshot:

![image](https://user-images.githubusercontent.com/1434387/40736886-83f6b07e-643f-11e8-87fa-c69bb3c4c9e3.png)

It will be great if the blue/gray table can be automatically resized if the text size is bigger.

Thank you...

**Comment by tnwhitwell** [comment]
Good find. I had noticed that text was truncated, but just dealt with it
for my own start page. Do you think just flowing text onto the new line
would be sensible behaviour, or were you thinking something else?

**Comment by ruzickap** [comment]
Actually it will be better if the "long text" will be on single long line and the table will resize to the text size - for both "- name: Test 12345678901234567890 12345678901234567890" and "- title: Test 12345678901234567890 12345678901234567890" if possible.

Thanks for your quick response...

**Comment by tnwhitwell** [comment]
I've taken a look into it, and I don't really like the outcome.

Possible fixes are changing the .link css to:

```css
.link {
    display: block !important;
    text-align: left !important;
    overflow: visible;
    height: auto !important;
    min-height: 36px;
    white-space: normal;
    word-wrap: break-word;
}
```

but this makes the line spacing look dumb: 

![image](https://user-images.githubusercontent.com/3595020/40840631-6db0bace-659f-11e8-8903-0326948aab20.png)

I'm sure there's something that can be done. I've committed the changes to feature/1-Resizable-Table. If you can make it look any better, please submit a pr!
